version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    
    env_file:
      - ./env.db

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./GoChatbotBackend
    ports:
      - "5000:5000"
    env_file:
      - ./GoChatbotBackend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./NextJSChatbotExample
    ports:
      - "3000:3000"
    env_file:
      - ./NextJSChatbotExample/.env
    depends_on:
      - backend

volumes:
  db_data: